import { CRMLead } from "./crm-store";

export async function exportAuditPDF(data: {
  analysis: Record<string, unknown>;
  crawlData: Record<string, unknown>;
  auditedAt: string;
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const a = data.analysis as Record<string, any>;
  const scores = a.scores as Record<string, number>;
  const estimated = a.estimatedProjectValue as Record<string, { min: number; max: number; reason: string }>;
  const summary = a.executiveSummary as Record<string, string[]>;

  const W = 210; const margin = 18;
  let y = 0;

  // Helper functions
  const hex2rgb = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b] as [number, number, number];
  };

  const fillRect = (x: number, yy: number, w: number, h: number, color: string) => {
    doc.setFillColor(...hex2rgb(color));
    doc.rect(x, yy, w, h, "F");
  };

  const text = (str: string, x: number, yy: number, opts?: { size?: number; color?: string; bold?: boolean; align?: "left" | "center" | "right" }) => {
    doc.setFontSize(opts?.size || 10);
    doc.setTextColor(opts?.color || "#1a1a2e");
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
    doc.text(str, x, yy, { align: opts?.align || "left" });
  };

  const wrap = (str: string, x: number, yy: number, maxW: number, opts?: { size?: number; color?: string; lineH?: number }) => {
    doc.setFontSize(opts?.size || 9);
    doc.setTextColor(opts?.color || "#333333");
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(str, maxW);
    doc.text(lines, x, yy);
    return yy + lines.length * (opts?.lineH || 4.5);
  };

  const newPage = () => {
    doc.addPage();
    y = 20;
    fillRect(0, 0, W, 12, "#0B1A2E");
    text("LeadHunter AI — Confidential Audit Report", margin, 8, { size: 7, color: "#00C8A8" });
    text(String(a.businessName || ""), W - margin, 8, { size: 7, color: "#888888", align: "right" });
    y = 20;
  };

  // COVER PAGE
  fillRect(0, 0, W, 297, "#05101F");
  fillRect(0, 0, W, 80, "#0B1A2E");

  // Logo area
  fillRect(margin, 20, 10, 10, "#00C8A8");
  text("LeadHunter", margin + 13, 28, { size: 16, color: "#FFFFFF", bold: true });
  text("AI", margin + 54, 28, { size: 16, color: "#00C8A8", bold: true });
  text("Agency Prospecting Platform", margin + 13, 34, { size: 7, color: "#637B96" });

  text("WEBSITE AUDIT REPORT", margin, 60, { size: 22, color: "#FFFFFF", bold: true });
  text(String(a.businessName || (data.crawlData.url as string)), margin, 70, { size: 12, color: "#00C8A8" });
  text(String(data.crawlData.url), margin, 77, { size: 8, color: "#637B96" });

  // Score boxes on cover
  const scoreItems = [
    { label: "Overall Score", val: scores?.overall || 0 },
    { label: "SEO Score", val: scores?.seo || 0 },
    { label: "Conversion", val: scores?.conversion || 0 },
    { label: "Automation", val: scores?.automation || 0 },
  ];
  let sx = margin;
  scoreItems.forEach(s => {
    fillRect(sx, 90, 40, 28, "#0F2040");
    doc.setDrawColor(0, 200, 168);
    doc.setLineWidth(0.5);
    doc.rect(sx, 90, 40, 28);
    text(String(s.val), sx + 20, 106, { size: 18, color: "#00C8A8", bold: true, align: "center" });
    text(s.label, sx + 20, 112, { size: 7, color: "#888888", align: "center" });
    sx += 43;
  });

  // Opportunity level badge
  const oppColor = (a.opportunityLevel as string) === "High" ? "#EF4444" : (a.opportunityLevel as string) === "Medium" ? "#F59E0B" : "#22C55E";
  fillRect(margin, 128, 80, 16, oppColor + "22");
  doc.setDrawColor(...hex2rgb(oppColor));
  doc.rect(margin, 128, 80, 16);
  text(`${a.opportunityLevel as string} OPPORTUNITY`, margin + 40, 138, { size: 10, color: oppColor, bold: true, align: "center" });

  // Estimated value
  if (estimated?.totalMin) {
    text("ESTIMATED PROJECT VALUE", margin, 155, { size: 8, color: "#637B96" });
    text(`PKR ${Math.round(Number(estimated.totalMin) / 1000)}k — PKR ${Math.round(Number(estimated.totalMax) / 1000)}k`, margin, 163, { size: 14, color: "#00C8A8", bold: true });
  }

  // Industry & date
  text(`Industry: ${String(a.industry || "")}  |  Audit Date: ${new Date(data.auditedAt).toLocaleDateString()}`, margin, 175, { size: 8, color: "#555577" });

  text("CONFIDENTIAL — Generated by LeadHunter AI", margin, 285, { size: 7, color: "#333355" });
  text("leadhunterai.vercel.app", W - margin, 285, { size: 7, color: "#333355", align: "right" });

  // PAGE 2 — Executive Summary
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#00C8A8");
  text("EXECUTIVE SUMMARY", margin + 3, y + 5.5, { size: 10, color: "#05101F", bold: true });
  y += 14;

  const sections3 = [
    { label: "Top 3 Problems", items: summary?.top3Problems || [], color: "#EF4444" },
    { label: "Top 3 Quick Wins", items: summary?.top3QuickWins || [], color: "#F59E0B" },
    { label: "Top 3 Revenue Opportunities", items: summary?.top3RevenueOpportunities || [], color: "#00C8A8" },
  ];

  sections3.forEach(s => {
    fillRect(margin, y, W - margin * 2, 7, "#0B1A2E");
    text(s.label.toUpperCase(), margin + 3, y + 5, { size: 8, color: s.color, bold: true });
    y += 10;
    (s.items as string[]).forEach((item, i) => {
      text(`${i + 1}.`, margin + 3, y, { size: 9, color: s.color, bold: true });
      y = wrap(item, margin + 9, y, W - margin * 2 - 9, { size: 9, color: "#333333" });
      y += 2;
    });
    y += 5;
  });

  // PAGE 3 — Scores
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#0F2040");
  text("OPPORTUNITY SCORE ENGINE", margin + 3, y + 5.5, { size: 10, color: "#00C8A8", bold: true });
  y += 14;

  const scoreRows = [
    { label: "Website Quality", val: scores?.websiteQuality || 0, desc: "Design, structure, mobile readiness" },
    { label: "SEO Score", val: scores?.seo || 0, desc: "Meta tags, schema, headings, alt texts" },
    { label: "Conversion Score", val: scores?.conversion || 0, desc: "CTAs, forms, booking, WhatsApp" },
    { label: "Automation Score", val: scores?.automation || 0, desc: "Analytics, chat, CRM signals" },
    { label: "Overall Score", val: scores?.overall || 0, desc: "Weighted composite score" },
  ];

  scoreRows.forEach(s => {
    const barColor = s.val >= 70 ? "#00C8A8" : s.val >= 40 ? "#F59E0B" : "#EF4444";
    text(s.label, margin, y + 4, { size: 9, color: "#222244", bold: true });
    text(String(s.val) + "/100", W - margin, y + 4, { size: 9, color: barColor, bold: true, align: "right" });
    y += 6;
    fillRect(margin, y, W - margin * 2, 4, "#E8EEF4");
    fillRect(margin, y, ((W - margin * 2) * s.val) / 100, 4, barColor);
    y += 6;
    text(s.desc, margin, y + 3, { size: 7, color: "#888888" });
    y += 8;
  });

  // PAGE 4 — Estimated Project Value
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#0F2040");
  text("ESTIMATED PROJECT VALUE", margin + 3, y + 5.5, { size: 10, color: "#00C8A8", bold: true });
  y += 14;

  if (estimated) {
    const valueItems = [
      { label: "Website Upgrade", data: estimated.websiteUpgrade },
      { label: "AI Chatbot", data: estimated.aiChatbot },
      { label: "CRM / Management System", data: estimated.crmSystem },
      { label: "WhatsApp Automation", data: estimated.whatsappAutomation },
    ];
    valueItems.forEach(v => {
      if (!v.data) return;
      fillRect(margin, y, W - margin * 2, 22, "#F8FAFF");
      doc.setDrawColor(220, 225, 240);
      doc.rect(margin, y, W - margin * 2, 22);
      text(v.label, margin + 4, y + 7, { size: 9, color: "#1a1a2e", bold: true });
      text(`PKR ${Math.round(v.data.min / 1000)}k — PKR ${Math.round(v.data.max / 1000)}k`, W - margin - 4, y + 7, { size: 10, color: "#00C8A8", bold: true, align: "right" });
      wrap(v.data.reason || "", margin + 4, y + 13, W - margin * 2 - 8, { size: 8, color: "#555555" });
      y += 26;
    });

    y += 4;
    fillRect(margin, y, W - margin * 2, 14, "#0B1A2E");
    text("TOTAL ESTIMATED OPPORTUNITY", margin + 4, y + 6, { size: 9, color: "#637B96", bold: true });
    text(`PKR ${Math.round(Number(estimated.totalMin) / 1000)}k — PKR ${Math.round(Number(estimated.totalMax) / 1000)}k`, W - margin - 4, y + 9, { size: 14, color: "#00C8A8", bold: true, align: "right" });
    y += 20;
  }

  // PAGE 5 — Outreach Templates
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#0F2040");
  text("PERSONALIZED OUTREACH TEMPLATES", margin + 3, y + 5.5, { size: 10, color: "#00C8A8", bold: true });
  y += 14;

  const outreach = a.outreach as Record<string, string | Record<string, string>>;
  if (outreach) {
    text("WHATSAPP MESSAGE", margin, y, { size: 8, color: "#25D366", bold: true });
    y += 5;
    fillRect(margin, y, W - margin * 2, 2, "#25D366");
    y += 5;
    y = wrap(String(outreach.whatsapp || ""), margin, y, W - margin * 2, { size: 9, color: "#333333", lineH: 5 });
    y += 8;

    const email = outreach.email as Record<string, string>;
    if (email) {
      text("EMAIL PITCH", margin, y, { size: 8, color: "#4A90E2", bold: true });
      y += 5;
      fillRect(margin, y, W - margin * 2, 2, "#4A90E2");
      y += 5;
      text(`Subject: ${email.subject || ""}`, margin, y, { size: 9, color: "#1a1a2e", bold: true });
      y += 6;
      y = wrap(String(email.body || ""), margin, y, W - margin * 2, { size: 9, color: "#333333", lineH: 5 });
      y += 8;
    }

    text("LINKEDIN MESSAGE", margin, y, { size: 8, color: "#0077B5", bold: true });
    y += 5;
    fillRect(margin, y, W - margin * 2, 2, "#0077B5");
    y += 5;
    y = wrap(String(outreach.linkedin || ""), margin, y, W - margin * 2, { size: 9, color: "#333333", lineH: 5 });
  }

  // PAGE 6 — Competitor Gap Analysis
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#0F2040");
  text("COMPETITOR GAP ANALYSIS", margin + 3, y + 5.5, { size: 10, color: "#00C8A8", bold: true });
  y += 14;

  const gaps = a.competitorGaps as Array<{ gap: string; present: boolean; impact: string; severity: string }>;
  if (gaps?.length) {
    gaps.forEach(g => {
      const sevColor = g.severity === "Critical" ? "#EF4444" : g.severity === "High" ? "#F97316" : g.severity === "Medium" ? "#F59E0B" : "#22C55E";
      fillRect(margin, y, W - margin * 2, 18, g.present ? "#F0FFF4" : "#FFF5F5");
      doc.setDrawColor(...hex2rgb(sevColor));
      doc.rect(margin, y, W - margin * 2, 18);
      fillRect(margin, y, 3, 18, sevColor);
      text(g.present ? "✓" : "✕", margin + 7, y + 8, { size: 10, color: g.present ? "#22C55E" : "#EF4444", bold: true });
      text(g.gap, margin + 14, y + 7, { size: 9, color: "#1a1a2e", bold: true });
      text(g.severity, W - margin - 2, y + 7, { size: 8, color: sevColor, bold: true, align: "right" });
      wrap(g.impact, margin + 14, y + 12, W - margin * 2 - 20, { size: 8, color: "#555555" });
      y += 22;
    });
  }

  // PAGE 7 — Recommended Services
  newPage();
  fillRect(margin, y, W - margin * 2, 8, "#0F2040");
  text("RECOMMENDED SERVICES TO PITCH", margin + 3, y + 5.5, { size: 10, color: "#00C8A8", bold: true });
  y += 14;

  const services = a.recommendedServices as Array<{ service: string; reason: string; priority: string; estimatedPrice: string }>;
  if (services?.length) {
    services.forEach((s, i) => {
      const pColor = s.priority === "High" ? "#EF4444" : s.priority === "Medium" ? "#F59E0B" : "#22C55E";
      text(`${i + 1}. ${s.service}`, margin, y, { size: 10, color: "#1a1a2e", bold: true });
      text(s.priority, W - margin, y, { size: 8, color: pColor, bold: true, align: "right" });
      y += 5;
      y = wrap(s.reason, margin + 4, y, W - margin * 2 - 4, { size: 8.5, color: "#444444" });
      text(s.estimatedPrice, margin + 4, y + 3, { size: 9, color: "#00C8A8", bold: true });
      y += 10;
    });
  }

  // Footer on last page
  text("Generated by LeadHunter AI — Agency Prospecting Platform", W / 2, 285, { size: 7, color: "#888888", align: "center" });

  const filename = `LeadHunter-Audit-${String(a.businessName || "Report").replace(/[^a-zA-Z0-9]/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

export function exportLeadsCsv(leads: CRMLead[]) {
  const headers = ["Business Name", "Website", "Industry", "Phones", "Emails", "Opportunity Level", "Score", "Value Min (PKR)", "Value Max (PKR)", "Outreach Status", "Audit Date", "Notes"];
  const rows = leads.map(l => [
    l.businessName, l.website, l.industry,
    l.phones.join("; "), l.emails.join("; "),
    l.opportunityLevel, l.opportunityScore,
    l.estimatedValueMin, l.estimatedValueMax,
    l.outreachStatus, l.auditDate, l.notes
  ]);
  const csv = [headers, ...rows].map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `LeadHunter-CRM-Export-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
}
